### ISSUE TITLE
Error: Cant find mono!

### ISSUE THREAD

**Issue by Techbrunch** [NorthwaveNL/fridax#1]
Hello,

Thanks for this project, it looks like this is what I was looking for.

I'm running into an issue when trying to run a script:

```
node fridax.js inject --scripts read_class_static_string_variable
[*] Awaiting storage initialization.
[*] Awaiting USB device.
[*] Up and running on Phone.
? Which application do you want to inject? Gadget
[*] Attached to application (session: 23972).
[*] Injected a test script (this runs from within the injected application)!
Error: Cant find mono!
    at node_modules/frida-mono-api/src/mono-module.js:7
    at o (node_modules/browser-pack/_prelude.js:1)
    at node_modules/frida-mono-api/src/mono-api.js:2
    at o (node_modules/browser-pack/_prelude.js:1)
    at /script2.js:119
    at o (node_modules/browser-pack/_prelude.js:1)
    at scripts/read_class_static_string_variable.js:1
    at o (node_modules/browser-pack/_prelude.js:1)
    at r (node_modules/browser-pack/_prelude.js:1)
[*] Happy hacking.
```

What I did was:

- Patch the APK using [Objection](https://github.com/sensepost/objection)
- Install the APK on the phone (real device)
- Start the APK
- Start Objection so that the app is running
- Run `node fridax.js inject`

Any idea of what could be wrong ?

**Comment by tijme** [comment]
Would it be possible to share the APK file, or is it confidential?

I must say that I haven't tested this script on Android (only on iOS), but nevertheless it should work on Android too. Are you sure it is a Xamarin application?

Also, make sure to run your application before running Fridax, as described in the [known issues](https://github.com/NorthwaveNL/fridax#issues).

**Comment by Techbrunch** [comment]
I can't share the APK but I have sent some info about it as a DM on Twitter.

I'm sure this is a Xamarin app.

I'm doing `objection explore` before doing the injection using Fridax so the app is running.

Note that I'm doing this on a Mac but I have Mono installed (using brew).

Frida version: 12.8.19
Mono version: 6.8.0.105
Objection version: 1.9.0
Gadget version: 12.8.19

**Comment by tijme** [comment]
Commit 192c6fe8a9cb743846f80b7a3090d8a52e74babb fixes this issue, as discussed on Twitter.

**Comment by Techbrunch** [comment]
@tijme Not sure if you saw that but the solution to our problem was right under our nose: https://github.com/freehuntx/frida-mono-api/pull/6/commits/615a6d45f3357df8dd845af784e8402c857d7a4f
